# Generated by Django 2.2 on 2020-06-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(default='', max_length=50)),
                ('calle', models.IntegerField(null=True)),
                ('comuna', models.CharField(default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('precio', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descuento', models.FloatField(null=True)),
                ('monto_final', models.FloatField(null=True)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('telefono', models.IntegerField(null=True)),
                ('web', models.CharField(default='', max_length=50)),
                ('rut', models.IntegerField(unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Categoria'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('telefono', models.IntegerField(null=True)),
                ('rut', models.IntegerField(unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresita.Venta')),
            ],
        ),
    ]
