# Generated by Django 2.2 on 2020-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='Numero',
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
