# Generated by Django 2.2 on 2020-06-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Proveedor'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Categoria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Producto'),
        ),
    ]
